### ISSUE TITLE
No module named 'plot_data'

### ISSUE THREAD

**Issue by BlindShrimp** [rhr407/EVAGAN#1]
there is no "plot_data"

**Comment by RizwanHamid** [comment]
Hi @OneoneWang: Thanks for highlighting this bug. I have resolved the issue now.

**Comment by BlindShrimp** [comment]
Excuse me,it is just a little problem,Using python3.9 and pip install plot-data,and it is done.

**Comment by RizwanHamid** [comment]
The plot_data was a local module that I was using previously in my code. I had not included that in this code. However, plot-data is a python module that is not being used in my code. I am happy that the issue is resolved on your end now :)

**Comment by BlindShrimp** [comment]
Sincerely thanks!
